(custom-set-variables
 '(pov-indent-under-declare 4 t)
 '(html-helper-build-new-buffer nil)
 '(mode-compile-reading-time 10)
 '(font-lock-auto-fontify t)
 '(cperl-continued-statement-offset 4)
 '(lazy-shot-verbose nil)
 '(sentence-end-double-space nil)
 '(font-menu-ignore-scaled-fonts nil)
 '(gutter-buffers-tab-visible-p nil)
 '(paren-mode (quote paren) nil (paren))
 '(sgml-indent-step 4 t)
 '(font-lock-maximum-decoration t)
 '(mode-compile-other-frame-p t)
 '(ruby-indent-level 4 t)
 '(cperl-label-offset 0)
 '(custom-buffer-sort-alphabetically t)
 '(pc-select-selection-keys-only t)
 '(html-helper-do-write-file-hooks nil)
 '(html-helper-use-expert-menu t)
 '(mode-compile-never-edit-command-p t)
 '(LaTeX-left-right-indent-level 2)
 '(TeX-brace-indent-level 4)
 '(ps-font-family (quote Courier))
 '(column-number-mode t)
 '(compilation-window-height 10)
 '(cperl-close-paren-offset 0)
 '(lazy-shot-mode t nil (lazy-shot))
 '(pov-indent-level 4 t)
 '(c-offsets-alist (quote ((access-label . -))))
 '(gnuserv-program (concat exec-directory "/gnuserv"))
 '(progress-feedback-use-echo-area nil)
 '(custom-buffer-indent 4)
 '(initial-scratch-message "" t)
 '(sgml-inhibit-indent-tags nil)
 '(lazy-shot-stealth-verbose nil)
 '(bar-cursor 2)
 '(case-fold-search nil)
 '(tab-width 4)
 '(show-paren-mode t nil (paren))
 '(c-default-style "java")
 '(lazy-shot-stealth-time nil)
 '(pending-delete-mode t nil (pending-del))
 '(cperl-highlight-variables-indiscriminately nil)
 '(LaTeX-indent-level 2)
 '(toolbar-visible-p nil)
 '(cperl-indent-level 4)
 '(truncate-lines t)
 '(scrollbars-visible-p nil)
 '(cperl-continued-brace-offset -4)
 '(mark-diary-entries-in-calendar t)
 '(line-number-mode t)
 '(cperl-min-label-indent 0)
 '(compilation-always-signal-completion t)
 '(pc-select-meta-moves-sexps t)
 '(mouse-yank-at-point t)
 '(blink-cursor-mode nil nil (blink-cursor))
 '(compilation-read-command t)
 '(LaTeX-item-indent -2)
 '(user-mail-address "greg@puyo.cjb.net")
 '(query-user-mail-address nil)
 '(mail-indentation-spaces 4)
 '(font-lock-mode t nil (font-lock))
 '(pc-selection-mode t t (pc-select)))
(custom-set-faces
 '(default ((t (:size "14pt" :family "courier"))) t)
 '(info-node ((t (:foreground "lightblue1" :bold t))))
 '(secondary-selection ((t (:background "darkorchid2"))) t)
 '(cperl-array-face ((((class color) (background dark)) (:foreground "yellow" :bold t))))
 '(font-lock-string-face ((((class color) (background dark)) (:foreground "aquamarine"))))
 '(paren-mismatch ((t (:foreground "yellow" :background "red"))) t)
 '(font-lock-reference-face ((((class color) (background dark)) (:foreground "aquamarine"))))
 '(isearch-secondary ((t (:foreground "pink"))) t)
 '(cperl-hash-face ((((class color) (background dark)) (:foreground "Red" :bold t :italic t))))
 '(font-lock-doc-string-face ((((class color) (background dark)) (:foreground "lightgoldenrod"))))
 '(modeline-buffer-id ((t (:foreground "khaki"))) t)
 '(font-lock-preprocessor-face ((((class color) (background dark)) (:foreground "goldenrod1"))))
 '(modeline-mousable ((t (:foreground "wheat"))) t)
 '(font-lock-variable-name-face ((((class color) (background dark)) (:foreground "khaki"))))
 '(font-pov-csg-face ((((class color) (background dark)) (:foreground "orange"))))
 '(gui-element ((t nil)) t)
 '(paren-match ((t (:foreground "black" :background "turquoise"))) t)
 '(modeline-mousable-minor-mode ((t (:foreground "goldenrod2"))) t)
 '(font-lock-keyword-face ((((class color) (background dark)) (:foreground "cyan"))))
 '(font-lock-type-face ((((class color) (background dark)) (:foreground "lightsteelblue1"))))
 '(bold ((t (:bold t))) t)
 '(bold-italic ((t (:bold t :italic t))) t)
 '(primary-selection ((t (:background "royalblue"))) t)
 '(blue ((t (:foreground "cornflowerblue"))) t)
 '(custom-button-face ((t (:bold t))))
 '(list-mode-item-selected ((t (:background "royalblue"))) t)
 '(custom-variable-button-face ((t (:bold t :underline t))))
 '(italic ((t (:italic t))) t)
 '(font-lock-comment-face ((((class color) (background dark)) (:foreground "gray80" :family "fixed"))))
 '(font-lock-function-name-face ((((class color) (background dark)) (:foreground "steelblue1"))))
 '(isearch ((t (:background "royalblue"))) t)
 '(highlight ((t (:background "darkseagreen4"))) t)
 '(modeline ((t nil)) t))

(set-specifier vertical-scrollbar-visible-p t)
