#!/usr/bin/env python

import os
import re
import sys
import time
import socket
import string
from subprocess import Popen, PIPE

HOST="localhost"
PORT=9876
NICK="pewp"
IDENT="pewp"
REALNAME="pewp"
BOT="lotusboob"

def red(t):
    return colour(5, t)

def yellow(t):
    return colour(7, t)

def green(t):
    return colour(3, t)

def colour(c, t):
    return chr(3) + str(c) + t + chr(3)

here = os.path.basename(os.getcwd())
if here == '.git':
    repo = os.path.basename(os.path.dirname(os.getcwd()))
else:
    repo = os.path.basename(os.getcwd()).replace('.git', '')

new, old, _ = sys.stdin.readlines()[0].split(' ')
if '0000000000000000000000000000000000000000' in [new, old]:
    sys.exit(0)

git_spam = Popen(['git', 'log', '--pretty=format:"[%s:%%h] %%an: %%s"' % repo, '%s..%s' % (new, old)], stdout=PIPE).communicate()[0]

s = socket.socket()
s.connect((HOST, PORT))
s.send("NICK %s\r\n" % NICK)
s.send("USER %s %s bla :%s\r\n" % (IDENT, HOST, REALNAME))
s.send("PRIVMSG %s :identify pewp pewp\r\n" % BOT)
for spam in git_spam.split('\n'):
    # [mooc.git:ab34dc2] Dave Turnbull: minor clenaup
    r = re.search('\[(.*?)\] (.*?): (.*)', spam)
    repo = r.group(1)
    committer = r.group(2)
    message = r.group(3)

    spam = '[%s] %s %s' % (yellow(repo), committer, green(message))

    s.send('PRIVMSG %s :say #passengers "%s\r\n' % (BOT, spam))
